[package]
name = "meteora-rpc-filters"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "2.0.19"
solana-account-decoder = "2.0.19"
solana-sdk = "2.0.19"
borsh = "1.5.3"
tokio = "1.42.0"
futures = "0.3.31"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
dotenvy = "0.15.7"
